import { Geist, Geist_Mono } from "next/font/google";
import "./../../globals.css";
import Header from "@/Components/Common/Header";
import Footer from "@/Components/Common/Footer";
import UserHeader from "@/Components/userDashboard/UserHeader";
import UserSidebar from "@/Components/userDashboard/UserSidebar";
import { RiDashboardFill } from "react-icons/ri";
import { HiMiniClipboardDocumentList } from "react-icons/hi2";
import { LuCircleUser } from "react-icons/lu";



const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Wealth Wise | user dashboard",
    description: "Generated by create next app",
};

// not root layout this is main layout

const routeList = [
    {
        name: "Dashboard",
        path: "/user",
        icon: <RiDashboardFill />
    },
    {
        name: "My Applied Insurance",
        path: "/user/my-applied-insurance",
        icon: <HiMiniClipboardDocumentList />
    },
    {
        name: "My Profile",
        path: "/user/profile",
        icon: <LuCircleUser />
    },
]


export default function Layout({ children }) {
    return (
        <div>
            <div className="min-h-screen bg-gray-100 flex flex-col">
                {/* Company Header */}
                <div className="flex flex-1">
                    {/* Sidebar */}
                    <UserSidebar routeList={routeList} />
                    {/* Main Content Area */}
                    <div className="flex-1 flex flex-col">
                        <UserHeader routeList={routeList} className="" />
                        <div className="flex-1 md:px-10 md:py-5 p-5 bg-white ">
                            {children}
                        </div>
                    </div>
                </div>

            </div>
        </div>
    );
}
